[package]
name = "clipcount"
version = "1.0.0"
edition = "2021"
description = "Counting words from the clipboard content."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
